# Generated by Django 5.0.1 on 2024-04-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='autre_fonction',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
