# Generated by Django 5.0.1 on 2024-04-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_personnel_autre_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='addresse_email',
            field=models.CharField(default='medecin1', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='connexion',
            field=models.BooleanField(default=False),
        ),
    ]
