# Generated by Django 5.0.1 on 2024-04-28 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_personnel_addresse_email_personnel_connexion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='img',
        ),
        migrations.RemoveField(
            model_name='page_carnet',
            name='examens',
        ),
        migrations.RemoveField(
            model_name='page_carnet',
            name='images',
        ),
        migrations.RemoveField(
            model_name='page_carnet',
            name='symptomes',
        ),
        migrations.AddField(
            model_name='examen',
            name='date_de_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='examen',
            name='date_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='examen',
            name='conclusion',
            field=models.TextField(default='aucune'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='parametres',
            field=models.TextField(default=''),
        ),
    ]
