# Generated by Django 5.0.1 on 2024-04-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_examen_img_remove_page_carnet_examens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='pages_carnet',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='symptome',
            old_name='page_carnets',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='allergie',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='donnees_basique',
            name='allergies',
        ),
        migrations.AddField(
            model_name='allergie',
            name='page',
            field=models.ManyToManyField(to='patient.page_carnet'),
        ),
        migrations.AddField(
            model_name='donnees_basique',
            name='page',
            field=models.ManyToManyField(to='patient.page_carnet'),
        ),
    ]
