# Generated by Django 5.0.1 on 2024-04-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_pages_carnet_examen_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_carnet',
            name='remarque',
        ),
        migrations.AddField(
            model_name='page_carnet',
            name='medecin_en_charge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.personnel'),
        ),
    ]
