# Generated by Django 5.0.1 on 2024-04-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_page_carnet_remarque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_carnet',
            name='conclusion',
            field=models.TextField(default='en attente de resultat examen'),
        ),
        migrations.AlterField(
            model_name='page_carnet',
            name='observation',
            field=models.TextField(default='RAS'),
        ),
    ]
