# Generated by Django 5.0.1 on 2024-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_page_carnet_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees_basique',
            name='poids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donnees_basique',
            name='taille',
            field=models.IntegerField(),
        ),
    ]
