# Generated by Django 5.0.1 on 2024-04-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_donnees_basique_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptome',
            name='page',
        ),
        migrations.AddField(
            model_name='symptome',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.page_carnet'),
        ),
    ]
