# Generated by Django 5.0.1 on 2024-04-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_symptome_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees_basique',
            name='page',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.carnet'),
        ),
    ]
