# Generated by Django 5.0.1 on 2024-04-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_donnees_basique_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergie',
            name='description',
            field=models.TextField(default=' aucune '),
        ),
        migrations.AlterField(
            model_name='allergie',
            name='page',
            field=models.ManyToManyField(to='patient.donnees_basique'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='date_fin',
            field=models.DateField(default=None),
        ),
    ]
