# Generated by Django 5.0.1 on 2024-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_allergie_description_alter_allergie_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
