# Generated by Django 5.0.1 on 2024-04-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_alter_examen_conclusion_alter_examen_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='page',
        ),
        migrations.AddField(
            model_name='examen',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.page_carnet'),
        ),
    ]
