# Generated by Django 5.0.1 on 2024-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_remove_examen_page_examen_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
