# Generated by Django 5.0.1 on 2024-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_hopital_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hopital',
            old_name='directeur',
            new_name='matricule',
        ),
        migrations.AddField(
            model_name='hopital',
            name='connexion',
            field=models.BooleanField(default=False),
        ),
    ]
