# Generated by Django 5.0.1 on 2024-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_alter_examen_date_de_debut_alter_examen_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='date_de_debut',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
