# Generated by Django 5.0.1 on 2024-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_alter_examen_date_de_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergie',
            name='type',
            field=models.CharField(default='aucun', max_length=50),
        ),
    ]
